Fix png not returning from getCoverFromLink
ynhhoJ/flibusta-api pull request #31
Opened 2022-09-06 16:00 UTC by antiss11

https://github.com/antiss11/flibusta-api/issues/1

2022-09-06 19:26 UTC, ynhhoJ requested changes

2022-09-07 02:13 UTC, antiss11 commented on src/flibustaOpdsApiHelper.ts
Done accf2999483d4926e0e2b52aede7e9b9fe288f64.

2022-09-07 06:33 UTC, ynhhoJ commented
Please check your code before pushing it to main branch with ESLint

![изображение](https://user-images.githubusercontent.com/22500212/188805668-b4caa03b-9933-4b45-bf14-9166fab18dd0.png)

2022-09-07 06:47 UTC, ynhhoJ requested changes

2022-09-07 06:47 UTC, ynhhoJ commented on src/flibustaOpdsApiHelper.ts
> +        // return new Promise(res => res(1));
Why do you leave this code here?

2022-09-07 06:47 UTC, ynhhoJ commented on src/flibustaOpdsApiHelper.ts
> +
Line 56 will cause [no-multiple-empty-lines](https://eslint.org/docs/rules/no-multiple-empty-lines) error, please, remove!

2022-09-07 15:38 UTC, antiss11 commented
![2022-09-07-183549_881x118_scrot](https://user-images.githubusercontent.com/14955003/188919759-ea83b5af-afde-43d5-9b93-c439f6ee73f1.png)
Fixed 14ea55fbfec686faeea16c93b58d3b03aaa354a8. Thanks for your response, it's a great experience for me!

2022-09-07 16:31 UTC, ynhhoJ approved these changes

2022-09-07 16:32 UTC, ynhhoJ commented
@antiss11 , thank you fore your contribution. Merged!

2022-09-07 16:32 UTC, merged